version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - nestjs-network

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass 3322
    volumes:
      - redis_data:/data
    networks:
      - nestjs-network

volumes:
  postgres_data:
  redis_data:

networks:
  nestjs-network:
    driver: bridge
